// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuanLyNhanSu.Models.Entities;

[Table("PhucLoi")]
public partial class PhucLoi
{
    [Key]
    public int PhucLoiId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string PhucLoiType { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Money { get; set; }

    [InverseProperty("PhucLoi")]
    public virtual ICollection<Position> Positions { get; set; } = new List<Position>();
}