// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using QuanLyNhanSu.Models.Entities;

namespace QuanLyNhanSu.Data.Context;

public partial class QLNSContext : DbContext
{
    public QLNSContext()
    {
    }

    public QLNSContext(DbContextOptions<QLNSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<Cong> Congs { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<PhucLoi> PhucLois { get; set; }

    public virtual DbSet<Position> Positions { get; set; }

    public virtual DbSet<Salary> Salaries { get; set; }

    public virtual DbSet<Schedule> Schedules { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("PK__Account__349DA5A6E899A3D1");
        });

        modelBuilder.Entity<Cong>(entity =>
        {
            entity.HasKey(e => e.CongId).HasName("PK__Cong__BE52BA818D8BFB08");

            entity.HasOne(d => d.Employee).WithMany(p => p.Congs).HasConstraintName("FK_EmployeeAttendance").OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId).HasName("PK__Employee__7AD04F113C020FB1");

            entity.HasOne(d => d.Account).WithOne(p => p.Employee).HasConstraintName("FK_Account");

            entity.HasOne(d => d.Position).WithMany(p => p.Employees).HasConstraintName("FK_Position");

            entity.HasOne(d => d.Salary).WithMany(p => p.Employees).HasConstraintName("FK_Salary");
        });

        modelBuilder.Entity<PhucLoi>(entity =>
        {
            entity.HasKey(e => e.PhucLoiId).HasName("PK__PhucLoi__E041D7C45D45EFCF");
        });

        modelBuilder.Entity<Position>(entity =>
        {
            entity.HasKey(e => e.PositionId).HasName("PK__Position__60BB9A79B67833A8");

            entity.HasOne(d => d.PhucLoi).WithMany(p => p.Positions).HasConstraintName("FK_PhucLoi");
        });

        modelBuilder.Entity<Salary>(entity =>
        {
            entity.HasKey(e => e.SalaryId).HasName("PK__Salary__4BE204572E084E79");
        });

        modelBuilder.Entity<Schedule>(entity =>
        {
            entity.HasKey(e => e.ScheduleId).HasName("PK__Schedule__9C8A5B4926A8D27B");

            entity.HasOne(d => d.Employee).WithMany(p => p.Schedules).HasConstraintName("FK_EmployeeSchedule");
        });
    }

}