// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuanLyNhanSu.Models.Entities;

[Table("Cong")]
public partial class Cong
{
    [Key]
    public int CongId { get; set; }

    [Column(TypeName = "date")]
    public DateTime NgayCham { get; set; }

    public TimeSpan CheckIn { get; set; }

    public TimeSpan CheckOut { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Status { get; set; }

    public int? EmployeeId { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("Congs")]
    public virtual Employee Employee { get; set; }
}