// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuanLyNhanSu.Models.Entities;

[Table("Employee")]
public partial class Employee
{
    [Key]
    public int EmployeeId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Gender { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Role { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Address { get; set; }

    public int? AccountId { get; set; }

    public int? PositionId { get; set; }

    public int? SalaryId { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("Employee")]
    public virtual Account Account { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<Cong> Congs { get; set; } = new List<Cong>();

    [ForeignKey("PositionId")]
    [InverseProperty("Employees")]
    public virtual Position Position { get; set; }

    [ForeignKey("SalaryId")]
    [InverseProperty("Employees")]
    public virtual Salary Salary { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();
}