// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuanLyNhanSu.Models.Entities;

[Table("Position")]
public partial class Position
{
    [Key]
    public int PositionId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string PositionName { get; set; }

    [Column(TypeName = "text")]
    public string Description { get; set; }

    public int Number { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal HeSo { get; set; }

    public int? PhucLoiId { get; set; }

    [InverseProperty("Position")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    [ForeignKey("PhucLoiId")]
    [InverseProperty("Positions")]
    public virtual PhucLoi PhucLoi { get; set; }
}