// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuanLyNhanSu.Models.Entities;

[Table("Salary")]
public partial class Salary
{
    [Key]
    public int SalaryId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string SalaryType { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Money { get; set; }

    [InverseProperty("Salary")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}